---
# tasks file for sshd

- name: OpenSSH Server and sudo should be installed
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openssh-server
    - sudo

- name: Add authorized SSH keys for these users
  authorized_key:
       user: root
#    key: "{{ lookup('file', item) }}"
       key: "{{ item }}"
  with_items:
       - "{{ ssh_pub_keys }}"
#  with_fileglob:
#    - "{{ sshd_auth_pub_dir }}"
  register: add_identity_key
  notify: restart sshd
  tags: 
    - keys

- name: Configure sshd
  when: add_identity_key|success and not add_identity_key|skipped # to prevent accidental lockouts
  lineinfile:
    dest: "{{ sshd_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    validate: "/usr/sbin/sshd -t -f %s"
  with_items:
    - { regexp: "^#?PermitRootLogin", line: "PermitRootLogin {{ permit_root_login }}" }
    - { regexp: "^#?PasswordAuthentication", line: "PasswordAuthentication {{ password_authentication }}" }
    - { regexp: "^#?PermitEmptyPasswords", line: "PermitEmptyPasswords {{ permit_empty_passwords }}" }
    - { regexp: "^#?ChallengeResponseAuthentication", line: "ChallengeResponseAuthentication {{ challenge_response_authentication }}" }
    - { regexp: "^#?UsePAM", line: "UsePAM {{ use_pam }}" }
  notify: restart sshd

